version: 0.2

phases:
  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION --registry-ids $ECR_ACCOUNT_ID)
      - REPOSITORY_URI=$ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
